// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEY6I12Qa-TX1b_sofEuX5hGu9u-0Dric',
    appId: '1:479915272465:web:3cb103711958e24fa104b0',
    messagingSenderId: '479915272465',
    projectId: 'strangelet-1ece9',
    authDomain: 'strangelet-1ece9.firebaseapp.com',
    storageBucket: 'strangelet-1ece9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2Lhoro0XgEhl_0duRiBF_oUS3Jer4IqA',
    appId: '1:479915272465:android:8629d4653ae56139a104b0',
    messagingSenderId: '479915272465',
    projectId: 'strangelet-1ece9',
    storageBucket: 'strangelet-1ece9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUBJPDG0jDBuLDEVRut0D3Mwns5M5VltA',
    appId: '1:479915272465:ios:e70b33cd1c10b94fa104b0',
    messagingSenderId: '479915272465',
    projectId: 'strangelet-1ece9',
    storageBucket: 'strangelet-1ece9.appspot.com',
    iosBundleId: 'com.example.strangelet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUBJPDG0jDBuLDEVRut0D3Mwns5M5VltA',
    appId: '1:479915272465:ios:8b5d8a9aa311f8b4a104b0',
    messagingSenderId: '479915272465',
    projectId: 'strangelet-1ece9',
    storageBucket: 'strangelet-1ece9.appspot.com',
    iosBundleId: 'com.example.strangelet.RunnerTests',
  );
}
